### ISSUE TITLE
[Crash] Does not use your newer core lib

### ISSUE THREAD

**Issue by AzrouStone** [SuperMartijn642/ScarecrowsTerritory#31]
**Version Info**
- Minecraft, 1.19.2
- Scarecrow's Territory, 1.1.11-fabric-mc1.19.2

**Steps to Reproduce**
Update the core lib to latest

**Crash report (~/logs/latest.log)**
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install supermartijn642configlib, version 1.1.0 or later.
More details:
	 - Mod 'Scarecrows' Territory' (scarecrowsterritory) 1.1.11 requires version 1.1.0 or later of supermartijn642configlib, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by SuperMartijn642** [comment]
> - Install supermartijn642configlib, version 1.1.0 or later.
More details:
> - Mod 'Scarecrows' Territory' (scarecrowsterritory) 1.1.11 requires version 1.1.0 or later of supermartijn642configlib, which is missing!
